
-- connect to your database of choice first!

CREATE SCHEMA XXX
       AUTHORIZATION ohdsi_admin;
COMMENT ON SCHEMA XXX
  IS 'Schema containing tables to support WebAPI functionality';
GRANT USAGE ON SCHEMA XXX TO PUBLIC;
GRANT ALL ON SCHEMA XXX TO GROUP ohdsi_admin;
GRANT USAGE ON SCHEMA XXX TO GROUP ohdsi_app;


ALTER DEFAULT PRIVILEGES IN SCHEMA XXX
    GRANT INSERT, SELECT, UPDATE, DELETE, REFERENCES, TRIGGER ON TABLES
    TO ohdsi_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA XXX
    GRANT SELECT, USAGE ON SEQUENCES
    TO ohdsi_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA XXX
    GRANT EXECUTE ON FUNCTIONS
    TO ohdsi_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA XXX 
    GRANT USAGE ON TYPES
    TO ohdsi_app;
