CREATE DATABASE XXX
  WITH ENCODING='UTF8'
       OWNER=ohdsi_admin
       CONNECTION LIMIT=-1;
GRANT ALL ON DATABASE XXX TO GROUP ohdsi_admin;
GRANT CONNECT, TEMPORARY ON DATABASE XXX TO GROUP ohdsi_app;


